# Generated by Django 5.0.6 on 2024-06-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('trainer', models.CharField(max_length=100)),
                ('years_raced', models.IntegerField(default=0)),
                ('percentage_wins', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'horses',
            },
        ),
    ]
